### ISSUE TITLE
should we add the analyize of corrected pacbio reads?

### ISSUE THREAD

**Issue by wangyugui** [schatzlab/SKBR3#1]
Hi.

Should we add the analyize of corrected pacbio reads?

For the pacbio reads without SV, the reads will be more close to the reference genome than other pacbio reads.

but for the pacbio reads with SV, the reads will be more close to other reads than the reference genome?

We can corrected the reads with CANU, and then map it to the reference genome?

Best Regards

**Comment by mschatz** [comment]
Thanks for your interest! The FALCON assembly and error corrected reads are hosted at DNAnexus: https://www.dnanexus.com/falcon 
I'll also add a link to the repo with the information.

Thanks!

Mike

**Comment by wangyugui** [comment]
@mschatz 

```
#samtools idxstats reads_lr_skbr3.fa_ngmlr-0.2.3_mapped.bam
...
X       155270560       890233  0
Y       59373566        8043    0
...
```

The reads mapped to Y because of mapping error or PAR#1 PAR#2 region in chrY?

Is the PAR#1 PAR#2 region in chrY  of this reference genome masked as N?

Best Regards

**Comment by mschatz** [comment]
We used the standard (unmasked) reference genome so these are likely to be
mismapped reads to the PAR regions. Note it is only ~8,000 reads compared
to over 800,000 so so it is less than 1% of the reads involved.

Cheers,

Mike
